// <auto-generated />
using System;
using CustomerApi.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerApi.Core.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260525064401_AddNewTables")]
    partial class AddNewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerApi.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("B2C");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2B",
                            Email = "alice.johnson@acme.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "(555) 100-1001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2B",
                            Email = "bob.smith@globex.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            Phone = "(555) 200-2002",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2B",
                            Email = "carol.w@initech.com",
                            FirstName = "Carol",
                            LastName = "Williams",
                            Phone = "(555) 300-3003",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2C",
                            Email = "david.brown@umbrella.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Phone = "(555) 400-4004",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2B",
                            Email = "eva.davis@wayneent.com",
                            FirstName = "Eva",
                            LastName = "Davis",
                            Phone = "(555) 500-5005",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2B",
                            Email = "frank.garcia@stark.com",
                            FirstName = "Frank",
                            LastName = "Garcia",
                            Phone = "(555) 600-6006",
                            Status = "Archived"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2C",
                            Email = "grace.m@oscorp.com",
                            FirstName = "Grace",
                            LastName = "Martinez",
                            Phone = "(555) 700-7007",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2B",
                            Email = "henry.r@lexcorp.com",
                            FirstName = "Henry",
                            LastName = "Rodriguez",
                            Phone = "(555) 800-8008",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2C",
                            Email = "irene.wilson@cyberdyne.com",
                            FirstName = "Irene",
                            LastName = "Wilson",
                            Phone = "(555) 900-9009",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2B",
                            Email = "james.a@weyland.com",
                            FirstName = "James",
                            LastName = "Anderson",
                            Phone = "(555) 101-0101",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2C",
                            Email = "karen.t@soylent.com",
                            FirstName = "Karen",
                            LastName = "Thomas",
                            Phone = "(555) 111-1111",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerType = "B2B",
                            Email = "leo.jackson@massive.com",
                            FirstName = "Leo",
                            LastName = "Jackson",
                            Phone = "(555) 121-2121",
                            Status = "Inactive"
                        });
                });

            modelBuilder.Entity("CustomerApi.Core.Entities.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StateProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses");
                });

            modelBuilder.Entity("CustomerApi.Core.Entities.CustomerBusinessProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LeadSource")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LifecycleStage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerBusinessProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Acme Corp",
                            CustomerId = 1,
                            LifecycleStage = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Globex Inc",
                            CustomerId = 2,
                            LifecycleStage = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Initech",
                            CustomerId = 3,
                            LifecycleStage = "Churned"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Umbrella LLC",
                            CustomerId = 4,
                            LifecycleStage = "Customer"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Wayne Enterprises",
                            CustomerId = 5,
                            LifecycleStage = "Customer"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Stark Industries",
                            CustomerId = 6,
                            LifecycleStage = "Churned"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Oscorp",
                            CustomerId = 7,
                            LifecycleStage = "Lead"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "LexCorp",
                            CustomerId = 8,
                            LifecycleStage = "Opportunity"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Cyberdyne Systems",
                            CustomerId = 9,
                            LifecycleStage = "Churned"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Weyland-Yutani",
                            CustomerId = 10,
                            LifecycleStage = "Customer"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Soylent Corp",
                            CustomerId = 11,
                            LifecycleStage = "Customer"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Massive Dynamic",
                            CustomerId = 12,
                            LifecycleStage = "Churned"
                        });
                });

            modelBuilder.Entity("CustomerApi.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagName = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            TagName = "Enterprise"
                        },
                        new
                        {
                            Id = 3,
                            TagName = "Startup"
                        });
                });

            modelBuilder.Entity("CustomerTag", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CustomerTag");
                });

            modelBuilder.Entity("CustomerApi.Core.Entities.CustomerAddress", b =>
                {
                    b.HasOne("CustomerApi.Core.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerApi.Core.Entities.CustomerBusinessProfile", b =>
                {
                    b.HasOne("CustomerApi.Core.Entities.Customer", "Customer")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("CustomerApi.Core.Entities.CustomerBusinessProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CustomerTag", b =>
                {
                    b.HasOne("CustomerApi.Core.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerApi.Core.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerApi.Core.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BusinessProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
