// <auto-generated />
using System;
using CustomerApi.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerApi.Core.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260513170232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerApi.Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Acme Corp",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice.johnson@acme.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            Phone = "(555) 100-1001",
                            Status = "active"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Globex Inc",
                            CreatedAt = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob.smith@globex.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            Phone = "(555) 200-2002",
                            Status = "active"
                        },
                        new
                        {
                            Id = 3,
                            Company = "Initech",
                            CreatedAt = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol.w@initech.com",
                            FirstName = "Carol",
                            LastName = "Williams",
                            Phone = "(555) 300-3003",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 4,
                            Company = "Umbrella LLC",
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david.brown@umbrella.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Phone = "(555) 400-4004",
                            Status = "active"
                        },
                        new
                        {
                            Id = 5,
                            Company = "Wayne Enterprises",
                            CreatedAt = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eva.davis@wayneent.com",
                            FirstName = "Eva",
                            LastName = "Davis",
                            Phone = "(555) 500-5005",
                            Status = "active"
                        },
                        new
                        {
                            Id = 6,
                            Company = "Stark Industries",
                            CreatedAt = new DateTime(2024, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank.garcia@stark.com",
                            FirstName = "Frank",
                            LastName = "Garcia",
                            Phone = "(555) 600-6006",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 7,
                            Company = "Oscorp",
                            CreatedAt = new DateTime(2024, 7, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "grace.m@oscorp.com",
                            FirstName = "Grace",
                            LastName = "Martinez",
                            Phone = "(555) 700-7007",
                            Status = "active"
                        },
                        new
                        {
                            Id = 8,
                            Company = "LexCorp",
                            CreatedAt = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "henry.r@lexcorp.com",
                            FirstName = "Henry",
                            LastName = "Rodriguez",
                            Phone = "(555) 800-8008",
                            Status = "active"
                        },
                        new
                        {
                            Id = 9,
                            Company = "Cyberdyne Systems",
                            CreatedAt = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "irene.wilson@cyberdyne.com",
                            FirstName = "Irene",
                            LastName = "Wilson",
                            Phone = "(555) 900-9009",
                            Status = "inactive"
                        },
                        new
                        {
                            Id = 10,
                            Company = "Weyland-Yutani",
                            CreatedAt = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "james.a@weyland.com",
                            FirstName = "James",
                            LastName = "Anderson",
                            Phone = "(555) 101-0101",
                            Status = "active"
                        },
                        new
                        {
                            Id = 11,
                            Company = "Soylent Corp",
                            CreatedAt = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "karen.t@soylent.com",
                            FirstName = "Karen",
                            LastName = "Thomas",
                            Phone = "(555) 111-1111",
                            Status = "active"
                        },
                        new
                        {
                            Id = 12,
                            Company = "Massive Dynamic",
                            CreatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "leo.jackson@massive.com",
                            FirstName = "Leo",
                            LastName = "Jackson",
                            Phone = "(555) 121-2121",
                            Status = "inactive"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
